### ISSUE TITLE
Make it run on a Linux box

### ISSUE THREAD

**Issue by christerjohansson** [alinzi/zencart-to-magento#1]
Hey,
Would it be possible to make this run on a Vagrant Linux box?
I am using the ScotchBox.io for a project, whic based on Ubuntu. And would like to convert a ZenCart with 2000 products into Magento with this little script. I am howevere recieving an error stating that 'root' argument is invalid for MySQL. I have installed MySQL connector and made sure I can connect from outside.

This is the output I get from my Ubuntu box,
`
File "zencart_to_magento.py", line 21, in <module>
    cnn=mysql.connector.connect(**config)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/__init__.py", line 98, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/connection.py", line 118, in __init__
    self.connect(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/connection.py", line 377, in connect
    self.config(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/connection.py", line 294, in config
    raise AttributeError("Unsupported argument '{0}'".format(key))
AttributeError: Unsupported argument 'vagrant'`

I am completely new to Python, so I don't really know how to operate it properly. :)

**Comment by christerjohansson** [comment]
May also mention that I ran this script through the compiler with,
`python -m py_compile zencart-to-magento.py`
before I executed it with normal python zencart-to-magento.pyc

**Comment by alinzi** [comment]
hi,the python version you used was 2.7? 
this python program need python version 3.x
please update you python version.

**Comment by christerjohansson** [comment]
Ok, I will try that.
Would this script be suitable for general conversion between ZenCart to Magento? :)
